# Read the README file for more detailed configuration information
# https://github.com/gpslab/geoip2
gpslab_geoip:
    # You should specify your personal licence key
    license: '%env(GEOIP2_LICENSE)%'

    # Edition ID of database you need
#    edition: 'GeoLite2-City GeoLite2-ASN GeoLite2-City GeoLite2-Country'
    edition: 'GeoLite2-City'
    path: '%kernel.project_dir%/src/geoip2db/GeoLite2-City.mmdb'
